#ifndef _BCM5325EMANAGELIB_H_
#define _BCM5325EMANAGELIB_H_

#define	GOBLEMANAGEREG		0x00
#define	VERSIONIDREG		0x02
#define	MIBMODEREG		0x04
#define	AGETIMECTRLREG		0x06
#define	MIRRORCAPTUREREG	0x10
#define	INGRESSMIRRORCTRLREG	0x12
#define	INGRESSMIRRORDIVDEREG	0x14
#define	EGRESSMIRRORCTRLREG	0x1C
#define	EGRESSMIRRORDIVDEREG	0x1E

#define	INBANDMANAGE		1
#define	NOMANAGEPORT		2

#define	ENABLEIGMP		1
#define	DISABLEIGMP		2

#define	ENABLERCVBPDU		1
#define	DISABLERCVBPDU		2

#define	MAXAGETIME		0x0FFFFF



#endif	/*_BCM5325EMANAGELIB_H_*/