/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.6 2006/04/18 17:36:16 hardaker Exp $
 */
#ifndef TRACE_PATH_MIB_H
#define TRACE_PATH_MIB_H

#ifdef __cplusplus
extern "C"{
#endif


/* function declarations */
void init_userTraceMib(void);
FindVarMethod var_userMacTraceTable;
FindVarMethod var_userLocationTable;
FindVarMethod var_vlanTraceTable;
    WriteMethod write_userLocRowStatus;


#ifdef __cplusplus
}
#endif

#endif /* TRACE_PATH_MIB_H */
